Kenan2000/CDDA-Structured-Kenan-Modpack

- Kenan-Modpack/Armor_Up!_Survivor_Expansion/Recipes.json
could prob be a bit more strict what proficiencies go too what recipe, but i think their mostly sensible.
> Add proficiencies too Armored up Survivor expansion recipes

- Kenan-Modpack/Dino_Mad_Science/monstergroups/dino_science_groups.json
Just changes some staff to zinos
> [Dino_Mad_Science]fixed some resort spawns

- Kenan-Modpack/Dino_Mad_Science/monsterdrops/dinodrops.json
- Kenan-Modpack/Dino_Mad_Science/monstergroups/dino_science_groups.json
- Kenan-Modpack/Dino_Mad_Science/monsters/prison_dinos_zinos.json
Hello prisons were empty and now theyre full of dino prisoners, cop dinos and robot cops! enjoy (commit is clean and pr is ready to merge Kenan)
> [Dino_Mad_Science] fixed and balanced prisons. added dino cops and prisoners

- Kenan-Modpack/Dino_Mad_Science/monstergroups/dino_science_groups.json
- Kenan-Modpack/Dino_Mad_Science/monsters/prison_dinos_zinos.json
accidentally balanced the original files for 50x spawn rate. this is balanced for ~1x spawn rate. tested and working. please push/merge through.
> [Dino_mad_science] Rebalancing work for prisons.

- Kenan-Modpack/Dino_Mad_Science/monsterdrops/dinodrops.json
- Kenan-Modpack/Dino_Mad_Science/monstergroups/dino_science_groups.json
- Kenan-Modpack/Dino_Mad_Science/monsters/prison_dinos_zinos.json
- Kenan-Modpack/Dino_Mad_Science/monsters/worker_dinos.json
hello medium update, ready to play.! adds dino fireman, technicians, and fixes prison zombifications/revives.
> [dino mad science]  add worker dinos and zombification versions of prison dinos and worker dinos

- Kenan-Modpack/Mutation-Changes-Snofielf-Patch-master/scenarios.json
I don't know if this will work, but hopefully it will.
> Fix overwriting lab escape start, hopefully

- Kenan-Modpack/Project_Kawaii/AMTS_container.json
The description specifically says it's folding, so it being rigid makes no sense.
> Changed the collapsable bottle to non-rigid

- Kenan-Modpack/Fallout_CDDA/med.json
- Kenan-Modpack/Fallout_CDDA/med_spawn.json
Adds Rad-X to the fallout mod, as I plan to expand how glowing deathclaws work, and also plan to add irradiated drinks and other comestibles from the fallout series.
> [Fallout] Add Rad-X

- Kenan-Modpack/Fallout_CDDA/monsters/undead.json
Very Minor tweak to glowing ones that makes them venomous, as it's the closest thing to radioactive at the moment as far as I can tell.
> [Fallout] Slight Tweak to Glowing Ones

- Kenan-Modpack/Battle_Maid_Redux/tool_armor.json
Should fix https://github.com/Kenan2000/CDDA-Kenan-Modpack/issues/97
> [Battle Maid] Fix Body Bag

- Kenan-Modpack/PKs_Rebalancing/pk_effects_override.json
- Kenan-Modpack/PKs_Rebalancing/pk_vitamins.json
A recent update made it so that these deficiencies are removed on load, so I made a quick fix for PK.
> [PK] Fix Vitamin Deficiencies Again

- Kenan-Modpack/Arcana/spells/spells_item.json
same as https://github.com/chaosvolt/cdda-arcana-mod/commit/7e96dea885697cb6b23d41dc7975d353121510f2
I do this by hand this time, I would like to know how you pick commit from other repo?
> Fix coalescent chalice fatigue

- Kenan-Modpack/XEAS/Mask.json
- Kenan-Modpack/aaa_NO_blacklist/gun/9mm.json
This prevents loading in latest experimental build
> Fix: duplicate ids

- Kenan-Modpack/PKs_Rebalancing/monsters/ant.json
- Kenan-Modpack/PKs_Rebalancing/monsters/blob.json
- Kenan-Modpack/PKs_Rebalancing/monsters/doom_revive.json
- Kenan-Modpack/PKs_Rebalancing/monsters/fungus.json
The game still crashes when it gets to crafting recipes, I don't know why.
> fix some things

- Kenan-Modpack/Jury_Rigged_Robots/jrr_rigged_bots.json
Fixes a legacy death function error in JRR as mentioned here: https://github.com/Kenan2000/CDDA-Kenan-Modpack/issues/120
> [ Jury Rigged Robots] Fix Error

- Kenan-Modpack/DeoxyMod/Deoxy_vehicle_parts.json
Upgraded and Quantum solar panels had same ID and volume, I fixed this.
Fixes #131
> [ Deoxy] Fix Duplicate ID

- Kenan-Modpack/Bootleg_Walkers/walker_item.json
Should be buckshot walker, not fusion walker
> [Bootleg Walkers]Fix name str

- Kenan-Modpack/nocts_cata_mod_DDA/Surv_help/c_armor.json
> [Cata++] Fix Typo

- Kenan-Modpack/Medieval_Mod_Reborn/chargen/mutations.json
- Kenan-Modpack/Medieval_Mod_Reborn/chargen/professions.json
Adds Knight Profession to Medieval Mod Reborn, 
Based on @squidboi937's PR linked here: https://github.com/CleverRaven/Cataclysm-DDA/pull/51148
> [MMR] Add Knight Profession

- Kenan-Modpack/GourmandsGraces/grocery1.json
> Just a little tweak 

- Kenan-Modpack/Dorf_Life/itemgroups.json
this fixes https://github.com/Kenan2000/CDDA-Kenan-Modpack/issues/155
> Fix tool_black_powder_bomb's removal

- Kenan-Modpack/Bugs_Life/monsters.json
- Kenan-Modpack/DracoDogMod/dog_monsters.json
- Kenan-Modpack/DracoPigMod/pig_monsters.json
- Kenan-Modpack/Mutant_Animals/monsters.json
- Kenan-Modpack/Mutant_Animals/mutant_birds.json
- Kenan-Modpack/Mutant_Animals/mutant_canines.json
- Kenan-Modpack/Mutant_Animals/mutant_ungulates.json
- Kenan-Modpack/Mutant_Insects/mutant_insect.json
- Kenan-Modpack/Mutant_Insects/mutant_spider.json
tested- can load into a world
do we update mods too keep pace for experimental, or stable? experimental, right?
> Update old animals too use the Jsonized Pet Food, from experimental.

- Kenan-Modpack/Slys_Beauteous_Beastly_Bugfix/Insect_Overwrites/sly_vespidae_overwrites.json
> Replace "upgrades" data with vanilla.

- Kenan-Modpack/Bootleg_Walkers/walker_recipes.json
- Kenan-Modpack/secronom_lore_expansion/Modification Files/Items/-Essentials/secro_item_groups.json
The variant of sig_assault_rifle is sig553.
Fix #197 
Fix #191
> variant fix

- Kenan-Modpack/World_On_Fire/items.json
- Kenan-Modpack/makeshift/item.json
DEBUG : Member material_thickness of type N4cata8optionalIfEE does not support relative
> Move material_thickness out of relative

- Kenan-Modpack/PKs_Rebalancing/pk_health_messages.json
> Fix: remove duplicated text

- Kenan-Modpack/PKs_Rebalancing/pk_overmap.json
Fixes https://github.com/Kenan2000/CDDA-Kenan-Modpack/issues/236
Seem to be affected by https://github.com/CleverRaven/Cataclysm-DDA/pull/52184
> Fix buggy spider_pit

- Kenan-Structured-Modpack/Archived-Mods/Battle_Maid_Redux/npcs/TALK_MAID_ALLY.json
- Kenan-Structured-Modpack/Archived-Mods/More_Survivors_Stories/mad_scientist/bg_mad_scientist.json
- Kenan-Structured-Modpack/Archived-Mods/Morlock_Village/NPC/TALK_MORLOCK_LIBRARIAN.json
- Kenan-Structured-Modpack/Archived-Mods/Psychiclysm/NPC/TALK_MESMER.json
- Kenan-Structured-Modpack/Archived-Mods/Recruitment_Options/TALK_RECRUIT.json
Same as chaosvolt/cdda-arcana-mod@099e6d0
And fix npc\_has\_trait\_flag for maid mod.
> fix: u_has_trait_flag and npc_has_trait_flag

- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/battoujutsu.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/clubstyle.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/flatmovecost.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/gunner.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/gunplay.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/hammertime.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/heavyknight.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/knifefighting.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/lancer.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/movecost1.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/movecost2.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/movecost3.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/speed1.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/speed2.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/speed3.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/staffstyle.json
- Kenan-Structured-Modpack/Archived-Mods/Abrahms_MartialArts/swordfighting.json
- Kenan-Structured-Modpack/Archived-Mods/CDDA_Sierra_Madre_mod/spells.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/BL9-100%_monster_resilience_version/Furniture-Terrain/terfurn_transform.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/BL9-140%_monster_resilience_version/Furniture-Terrain/terfurn_transform.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/BL9-175%_monster_resilience_version/Furniture-Terrain/terfurn_transform.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/MagicRevampAdditions/ter_furn_transform.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/secronom/Modification_Files/Maps/-Essentials/ter_furn_trans.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/secronom_lore_expansion/Modification Files/Items/secro_key.json
- README.md
As CleverRaven/Cataclysm-DDA#55538 invalidate it.
> FIx fail_message not valid

- Kenan-Structured-Modpack/Archived-Mods/Pneumatic_fun/Recipes/Recipes_ammo.json
Corrects an error popup on initialization due to not being defined
> Correct Recipe result

- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/World_On_Fire/itemgroups.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/World_On_Fire/monsters.json
cdda-windows-tiles-x64-msvc-2023-03-24-1552
> World_On_Fire

- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/Dino_Mad_Science/laser_items.json
Same as DDA to clear debug msg.
> Update ascii_picture of light_minus_battery_cell
