- Kenan-Modpack/laser_dinos_zinos/monstergroups/laser_dinos_zinos.json
couldnt really find any in my testing naturally (such a low chance), so decreased the weight to more closely follow dinomod spawn rates for large scary cbm dino bosses in the lab variations that call upon these monster groups. tested and found one in central lab at 50x spawn rate world setting. proves it's working. no errors found.
my justification is that the monsters are not as hard as they seem, a 20 rounds of a decent caliber will solve the laser dino fast, and i believe everything is better with laser dinos.
> rebalance laser dino spawns to be more common/possible to find.

- Kenan-Modpack/CDDA_Sierra_Madre_mod-master/effects.json
- Kenan-Modpack/CDDA_Sierra_Madre_mod-master/npcs/dialogue_fountain.json
This is my first commit to The Modpack / CDDA  and I'm also quite new to CDDA in general. As such I'm not very familiar with how things should and shouldn't be done in mods, and what json members have been introduced, deprecated etc. 
I assume the errors I've cleared up here are a result of the bodyparts/bp member being deprecated, although they do still show in the effects doc, so I'm not really sure.
> Sierra Madre Mod Error Fixes

- Kenan-Modpack/Artyom_Emporium_v.1/art_ammo.json
Changed Ammo damage type from stab to bullet
---
Bullets themselves did not show any damage info on the examine panels.
Magazines loaded with them had no damage value on the reload screen.
Guns loaded with *Match* bullets were doing zero damage, and had crazy dispersion spray.
Likely because they'd apply proportional damage to the base item with a wrong damage type, so it would base off zero.
> Artyom's Emporium - Change ammo damage type from 'stab' to 'bullet'

- Kenan-Modpack/Project_Kawaii/items.json
Fixed bags. They lacked any max encumbrance cap (causing encumbrance to skyrocket to 90+ when filled). They were also coded as soft, cloth containers like a backpack despite being described as hard-case containers, so materials were changed from cotton to plastic/steel. Also added water_friendly and sturdy similar to other hardcase containers in CDDA (like the violin case).
> Fixed kawaii bags

- Kenan-Modpack/More_Military/hecu.json
`hecu` starting profession is repeated in `Kenan-Modpack/More_Military/cs_scenarios.json` and [causes loading error](https://github.com/CleverRaven/Cataclysm-DDA/pull/48470):
> Remove duplicate "hecu" starting profession in More Military mod

- Kenan-Modpack/Project_Kawaii/AMTS_recipes.json
- The recipe for converting T1 packages into points does not appear in-game, even when using the "unlock all recipes" debug cheat. So I removed T1 resource packages were removed to prevent confusion, at least until the issue could be figured out.
- The AMTS Transmitter and Receiver were not appearing in their relevant itemgroup spawn locations. Not sure why exactly, but as a workaround made them craftable so they can still be obtained.
> Bug workarounds added to recipes

- Kenan-Modpack/Modular_Turrets/monster.json
The amount of ammo dropped is static so I used really low numbers since they are now a guaranteed source of ammo, this way a player who kills the 4 turrets to military bunker entrance isn't all of a sudden swimming in 10,000 rounds of 556
> Update modular turrets to drop ammo

- Kenan-Modpack/Modular_Turrets/monster_override.json
Hub01 have a mission that ask to bring back a bot, and generated mission target is unable to revert to item, due to lack of `revert_to_itype` in JSON.
I try add this and that mission is OK now (can "e" to bring bot back to item to hand for the mission), so I bring it here so this fix can be used by every one.
> fix: Modular_Turrets overwrite makes hub01 mission unable to complete

- Kenan-Modpack/easy_proficiency/modinfo.json
- Kenan-Modpack/easy_proficiency/proficiencies/chemistry.json
- Kenan-Modpack/easy_proficiency/proficiencies/electronics.json
- Kenan-Modpack/easy_proficiency/proficiencies/gunsmithing.json
- Kenan-Modpack/easy_proficiency/proficiencies/metalwork.json
- Kenan-Modpack/easy_proficiency/proficiencies/misc.json
- Kenan-Modpack/easy_proficiency/proficiencies/tailoring.json
- Kenan-Modpack/easy_proficiency/proficiencies/traps.json
- Kenan-Modpack/easy_proficiency/proficiencies/wilderness.json
- Kenan-Modpack/easy_proficiency/proficiencies/woodworking.json
There seems to be a lot of players who hate the proficiency system that was added.
Reduce all the proficiencies that can be learned learn time to 1 second. The player will get them instantly as long as they have the requirements.
None
Tested crafting several items and doing activities that give proficiency.
I automated the process with a script, I don't think there are any proficiencies which need to be edited manually but it could happen.
>  Add Easy Proficiencies: Removing proficiencies learn time

- Kenan-Modpack/PKs_Rebalancing/monsters/cult.json
Gives Homunculus description from Arcana, for compatibility and also because PK Homunculus needed description.
> [PK] Give Homunculus description

- Kenan-Modpack/AdvancedGear_CDDA_Mod/items/vehicle/vehicle_parts.json
- Kenan-Modpack/Arcana/vehicleparts.json
- Kenan-Modpack/Fallout_CDDA/vehicle_parts.json
- Kenan-Modpack/HeavyMining/parts.json
- Kenan-Modpack/PKs_Rebalancing/items/vehicle_parts.json
- Kenan-Modpack/Tankmod_Revived/treads.json
- Kenan-Modpack/blazemod/vehicleparts/flags.json
- Kenan-Modpack/cdda_variety_pack/vehicleparts/tanks.json
- Kenan-Modpack/secronom_lore_expansion/Modification Files/Others/secro_vehicleparts.json
Fixes the new warnings when loading certain vehicle mods, in the simplest way possible. I think I got them all.
Background: CleverRaven/Cataclysm-DDA#49193 added a check for vehicle part flags without definitions, but only flags used by the base game and in-repository mods were added to DDA. Some obsoleted, legacy, or mod-only flags weren't included. TRACKED was a big one, since lots of mods add tanks but there are none in the core game. I went here first because it's the biggest repository of mods I'm aware of at the moment; let me know if you know of any other big packs or any mod authors who'll need to update their own repositories.
Doesn't actually fix mods using broken flags, just clears the warnings. For example, I think the TOOL_X flags don't have an implementation in C++ anymore.
> Add missing flags to vehicle mods

- Kenan-Modpack/MMA_Mods_Extension/modinfo.json
Fixes dependencies of MMA Mod Extensions which fixes loading errors which are causing crashes as pointed out in https://github.com/Kenan2000/CDDA-Kenan-Modpack/issues/98
> [MMA-Extension] Fix Dependencies

- Kenan-Modpack/Arcana/vehicleparts.json
porting https://github.com/chaosvolt/cdda-arcana-mod/pull/184
vehicle_part not supporting EMITTER anymore? I tried after this fix it stop the warning.
> fix: vehicle part distorion_amp_motor_part has unknown flag EMITTER

- Kenan-Modpack/PKs_Rebalancing/monsters/fungus.json
Changes Fungal Boomer's death to fungalburst, as boomers splitting into two on death seems like an odd choice, unless that is intended by @meelock, in which case I will close this.
> [PK] Minor Tweak to Fungal Boomer

- Kenan-Modpack/secronom_lore_expansion/Modification Files/Items/Armors/secro_power_armor_armaments.json
When you make one of these and walk a step, the game complains about the lack of a material. This minor change silences that. Incidentally, did you know the game was calculating wind resistance for worn items based on their materials? Pretty cool.
> Kill the wind resist error due to being made of nothing.

- Kenan-Modpack/Fallout_CDDA/monsters/monstergroups.json
Moves ghouls to the sewer group, as it is more fitting with fallout lore and this way I know for certain that they are spawning.
> [Fallout] Move Ghouls to the sewers

- Kenan-Modpack/Psychiclysm/skills.json
But I don't know what's the proper name of this category, or just put it into Interaction skills.
Without screenshot because of the item group bug of Arcana.
EDIT:
This pr is to fix:
> [Psychiclysm]Missing "skill_display_type"

- Kenan-Modpack/easy_proficiency/proficiencies/chemistry.json
- Kenan-Modpack/easy_proficiency/proficiencies/comestibles.json
- Kenan-Modpack/easy_proficiency/proficiencies/electronics.json
- Kenan-Modpack/easy_proficiency/proficiencies/gunsmithing.json
- Kenan-Modpack/easy_proficiency/proficiencies/metalwork.json
- Kenan-Modpack/easy_proficiency/proficiencies/misc.json
- Kenan-Modpack/easy_proficiency/proficiencies/tailoring.json
- Kenan-Modpack/easy_proficiency/proficiencies/traps.json
- Kenan-Modpack/easy_proficiency/proficiencies/weakpoints.json
- Kenan-Modpack/easy_proficiency/proficiencies/wilderness.json
- Kenan-Modpack/easy_proficiency/proficiencies/woodworking.json
Update of the Easy Proficiencies mod.
Extract and run the proficiencies generation script in the mod folder.
Lint the json files.
Tested in-game, proficiencies were learned instantly as expected.
No issues encountered.
The game now has the archery proficiencies, three of them, with each proficiency reducing required strength for bows by one. This means essentially all bows had their required strength values reduced by -3.
The high amount of lines added and removed is due to linting the JSON file which I did not do previously.
> Update Easy Proficiencies mod

- Kenan-Structured-Modpack/Archived-Mods/PKs_Rebalancing/items/comestible.json
This is causing https://discourse.cataclysmdda.org/t/how-to-debug-tried-to-put-an-item-mre-bag-count-1-in-a-container/27583
> fix: delete misused overwride of gummy vitamins

- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/BL9-100%_monster_resilience_version/Locations/City_Locations.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/BL9-140%_monster_resilience_version/Locations/City_Locations.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/BL9-175%_monster_resilience_version/Locations/City_Locations.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/MagicRevampAdditions/traits/attunements.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/Miscellaneous_Magiclysm_Expansions/mutagenics/mutations/magic.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/Miscellaneous_Magiclysm_Expansions/mutagenics/mutations/orc.json
- Kenan-Structured-Modpack/High-Maintenance-Huge-Mods/secronom_lore_expansion/Modification Files/Others/secro_mutation.json
Resolves issues from https://github.com/CleverRaven/Cataclysm-DDA/pull/72173 etc. 
Only these mods were checked:
- BL9
- MagicRevampAdditions
- Miscellaneous_Magiclysm_Expansions
- MMA_Mods_Extension
- secronom
- secronom_lore_expansion
> Update to resolve errors caused by upstream changes
